// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiRhMySql.Context;

namespace apiRhMySql.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("apiRhMySql.Models.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdSetor")
                        .HasColumnType("int");

                    b.HasKey("IdCargo");

                    b.HasIndex("IdSetor");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("apiRhMySql.Models.Colaborador", b =>
                {
                    b.Property<int>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Admissao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Gestor")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdCargo")
                        .HasColumnType("int");

                    b.Property<int>("IdSetor")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<float>("Salario")
                        .HasColumnType("float");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Matricula");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdSetor");

                    b.ToTable("Colaborador");
                });

            modelBuilder.Entity("apiRhMySql.Models.Setor", b =>
                {
                    b.Property<int>("IdSetor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdSetor");

                    b.ToTable("Setor");
                });

            modelBuilder.Entity("apiRhMySql.Models.Cargo", b =>
                {
                    b.HasOne("apiRhMySql.Models.Setor", "Setor")
                        .WithMany("Cargos")
                        .HasForeignKey("IdSetor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("apiRhMySql.Models.Colaborador", b =>
                {
                    b.HasOne("apiRhMySql.Models.Cargo", "Cargo")
                        .WithMany("Colaboradores")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apiRhMySql.Models.Setor", "Setor")
                        .WithMany("Colaboradores")
                        .HasForeignKey("IdSetor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("apiRhMySql.Models.Cargo", b =>
                {
                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("apiRhMySql.Models.Setor", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("Colaboradores");
                });
#pragma warning restore 612, 618
        }
    }
}
